//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG6.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int IdComentario { get; set; }
        public int IdProducto { get; set; }
        public int IdUsuario { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
